### ISSUE TITLE
Blinking window without any blocks after build | Server is not running

### ISSUE THREAD

**Issue by mrobotby** [carlosperate/ardublockly#135]
Hi. I have built your program successfully (Windows 10 x64), but when I run program only blinking window appears without anything:( Do you know where is the problem? I use Python 2.7. In Python I'm noob) I'm really appreciate, if you can help me with this. 
2017-01-06T16:46:55.333Z - info: [ArdublocklyElec] Starting Ardublockly version: 0.1.2
2017-01-06T16:46:55.334Z - info: [ArdublocklyElec] Ardublockly root dir: C:\ardublockly_Windows64_2017-01-06_19.43
2017-01-06T16:46:55.334Z - info: [ArdublocklyElec] OS detected: win32
2017-01-06T16:46:55.440Z - info: [ServerMgr] Command: C:\ardublockly_Windows64_2017-01-06_19.43\arduexec\server\start.exe --findprojectroot --nobrowser
2017-01-06T16:46:55.580Z - error: [ArdublocklySrv] Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
    import linecache
ImportError: No module named linecache
Traceback (most recent call last):
  File "start.py", line 10, in <module>
    from __future__ import unicode_literals, absolute_import
ImportError: No module named __future__

2017-01-06T16:46:55.585Z - info: [ArdublocklySrv] Process exited with code 255
2017-01-06T16:46:59.039Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:00.790Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:01.472Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:03.197Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:03.878Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:05.606Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:06.289Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:08.011Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:08.689Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:10.420Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:11.091Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:12.821Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:13.494Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:15.220Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:15.903Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:17.622Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:18.308Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:20.022Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:20.715Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:22.419Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:23.116Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-06T16:47:24.909Z - info: [ArdublocklyElec] Starting Ardublockly version: 0.1.2
2017-01-06T16:47:24.911Z - info: [ArdublocklyElec] Ardublockly root dir: C:\ardublockly_Windows64_2017-01-06_19.43
2017-01-06T16:47:24.911Z - info: [ArdublocklyElec] OS detected: win32
2017-01-06T16:47:24.948Z - info: [ServerMgr] Command: C:\ardublockly_Windows64_2017-01-06_19.43\arduexec\server\start.exe --findprojectroot --nobrowser
2017-01-06T16:47:25.025Z - error: [ArdublocklySrv] Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
    import linecache
ImportError: No module named linecache
Traceback (most recent call last):
  File "start.py", line 10, in <module>
    from __future__ import unicode_literals, absolute_import
ImportError: No module named __future__

2017-01-06T16:47:25.053Z - info: [ArdublocklySrv] Process exited with code 255
<img width="960" alt="2017-01-06 19 54 21" src="https://cloud.githubusercontent.com/assets/14249390/21725659/73a21398-d44a-11e6-8f5f-295ae1b1a83d.png">

WHAT I DO TO BUILD. 
Step 1.
I open IDLE, open build.py file. Then I press F5 to run it.
Here you can see picture, after this I press Enter and go to do next step.
<img width="960" alt="2017-01-06 20 58 18" src="https://cloud.githubusercontent.com/assets/14249390/21727621/3d4e7abc-d453-11e6-9ba4-59f14214c2bf.png">
Step 2.
I open file build_py2exe.py.
<img width="960" alt="2017-01-06 20 59 04" src="https://cloud.githubusercontent.com/assets/14249390/21727652/624b4ba6-d453-11e6-89e8-d23d2542cb0d.png">
<img width="960" alt="2017-01-06 21 00 18" src="https://cloud.githubusercontent.com/assets/14249390/21727666/658cb20a-d453-11e6-9faa-b8248657d6db.png">
Step 3.  When first time I run this 
cd package\electron
npm install
npm run release
After I just run in CMD only one command - npm run release
<img width="960" alt="2017-01-06 21 04 47" src="https://cloud.githubusercontent.com/assets/14249390/21727745/ce0a7786-d453-11e6-8339-d1cb4d15bd12.png">
<img width="960" alt="2017-01-06 21 05 19" src="https://cloud.githubusercontent.com/assets/14249390/21727747/cf547394-d453-11e6-839c-1a8dd07af7fe.png">
Step 4. I run build_docs.py file
<img width="960" alt="2017-01-06 21 05 58" src="https://cloud.githubusercontent.com/assets/14249390/21727767/e610d21c-d453-11e6-8ed6-92f005f21d68.png">
Step 5. Python package. It seems to be working well.
![Uploading Скриншот 2017-01-06 21.07.06.png…]()
![Uploading Скриншот 2017-01-06 21.09.01.png…]()

**Comment by mrobotby** [comment]
I found that this problem I can avoid if before I start start.py file. Then I close web interface. Then I open ardublockly_run to run desktop application and all is working well. But when I try to start desktop application without starting start.py -nothing working, apears problem which I described above.

**Comment by MarceloFariaz** [comment]
I have the same problem. My ardublockly.log below:

2017-01-10T19:24:58.556Z - info: [ArdublocklyElec] Starting Ardublockly version: 0.1.2
2017-01-10T19:24:58.558Z - info: [ArdublocklyElec] Ardublockly root dir: C:\...\ardublockly_Windows32_2017-01-10_12.32
2017-01-10T19:24:58.558Z - info: [ArdublocklyElec] OS detected: win32

2017-01-10T19:24:58.578Z - info: [ServerMgr] Command: C:\...\ardublockly_Windows32_2017-01-10_12.32\arduexec\server\start.exe --findprojectroot --nobrowser


2017-01-10T19:24:58.645Z - error: [ArdublocklySrv] Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
    import linecache
ImportError: No module named linecache
Traceback (most recent call last):
  File "start.py", line 10, in <module>
ImportError: No module named __future__

2017-01-10T19:24:58.649Z - info: [ArdublocklySrv] Process exited with code 255

2017-01-10T19:25:01.091Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-10T19:25:02.841Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-10T19:25:03.510Z - warn: [ArdublocklyElec] Page failed to load (-102). The server is probably not yet running. Trying again in 200 ms.
2017-01-10T19:25:04.028Z - warn: [ArdublocklyElec] Page failed to load (0). The server is probably not yet running. Trying again in 200 ms.

The compiled version works fine, but the distributable form does not.

**Comment by mrobotby** [comment]
Help us, please!

**Comment by carlosperate** [comment]
Hi,

When running the build scripts it's better to do it from the command line. I haven't really IDLE much, but I would that some of the error you are getting on those screenshots are because of that.

About running the start.py and desktop application together: You can only run one or the other. If there has been errors in the application sometimes the server might be left behind, so I would recommend checking your task manager to kill any outstanding instances.
If the desktop application does not work, and then you run start.py and the desktop application starts working then there is a problem starting the server.

Could you try running the build scripts from the command line interface and see if the server has been built correctly? It should be in `arduexec\server\start.exe`.

**Comment by carlosperate** [comment]
@MarceloFariaz Could you let me know how have you downloaded, built, or installer Ardublockly?

**Comment by MarceloFariaz** [comment]
Hey, @carlosperate !

I followed step-by-step according to the Building Ardublockly documentation, from the download of GitHub to the final step: Packing all Ardublockly. I used the Windows Command Processor to run each command line as an administrator, all time.

**About my setup of the Ardublockly executable build dependencies:**
Git version 2.10.0.windows.1
Python 2.7.12
Node v4.5.0
Mkdocs, version 0.16.1
Py2exe v0.6.9
pyinstaller v3.2

**About the import error on my ardublockly.log:**
ImportError: No module named linecache
![image](https://cloud.githubusercontent.com/assets/12167941/21861363/b7dcf422-d81b-11e6-83f9-c338fc4268c4.png)
ImportError: No module named future
![image](https://cloud.githubusercontent.com/assets/12167941/21861375/c589463e-d81b-11e6-90b1-ed26d5c7491f.png)

Thank you for your attention!=)

**Comment by mrobotby** [comment]
Now is my turn to check @carlosperate recommendations:)

**Comment by mrobotby** [comment]
All is working if you will build build.py with Python27, and other files you will build with Python34 from CMD! Thank you @carlosperate 
But... I think I will have enough questions, because I'm going to add my own blocks to the application.

**Comment by MarceloFariaz** [comment]
I still can not solve my problem. I tried using both versions of Python27 and Python34, but I still have the same result. I think it's something related to the Python + py2exe configuration, but I still can not find anything that would help me solve this problem. =/

**Comment by MarceloFariaz** [comment]
@mrobotby can you tell me exactly which versions of the Ardublockly executable build dependencie you got made it work?

About my setup of the Ardublockly executable build dependencies:
Git version 2.10.0.windows.1
Python 2.7.12
Node v4.5.0
Mkdocs, version 0.16.1
Py2exe v0.6.9
pyinstaller v3.2

**Comment by MarceloFariaz** [comment]
@carlosperate could you look at this link: http://www.py2exe.org/index.cgi/ProblemsToBeFixed ? I did not quite understand, but apparently it has to do with the problem I am facing. Thanks for your help!

**Comment by carlosperate** [comment]
@MarceloFariaz could you open a new issue summarising your problem? It'd make it a lot easier to track and figure out.

**Comment by carlosperate** [comment]
>All is working if you will build build.py with Python27, and other files you will build with Python34 from CMD! Thank you @carlosperate

@mrobotby This issue seems different than the one you've mentioned in https://github.com/carlosperate/ardublockly/issues/142, is it safe to close this one and continue in a new one for that specific problem?

**Comment by carlosperate** [comment]
Since the original issue has been addressed and a new one opened to track the other problem I'm closing this one.
