### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by AlanMThomason** [carlosperate/ardublockly#242]
First off, thanks to everyone who brought this project to the public.  It is really amazing.  I am trying to set this up for a classroom, and I think this is great path.  I have added some blocks to allow adjusting servo speed and set up and read a serial stream on an arbitrary channel.  I am running it using

python start.py  (where my default python is 3.7.9)

I can successfully build the step ...\blockly>c:\python27\python build.py

But when I try to build the package, I see an error...

C:\SVN_working\ardublockly_at.git\trunk\package\electron>npm run release

> @ release C:\SVN_working\ardublockly_at.git\trunk\package\electron
> gulp release --env=production

fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\SVN_working\ardublockly_at.git\trunk\package\electron\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\SVN_working\ardublockly_at.git\trunk\package\electron\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\SVN_working\ardublockly_at.git\trunk\package\electron\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ release: `gulp release --env=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alanm\AppData\Roaming\npm-cache\_logs\2021-07-07T23_55_49_422Z-debug.log

My npm version is 
C:\SVN_working\ardublockly_at.git\trunk\ardublockly>npm --v
6.14.13

Can anyone see what I am doing wrong (or is there something other information needed).  Thanks in advance.

**Comment by MrKumakun** [comment]
The gulp version included in recent Node is version 4, so gulp 3.x and graceful-fs 3.x has occurred.

`npm ls graceful-fs`

```(...)
│
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3
│   └── graceful-fs@3.0.12
```

Open "package-lock.json" generated by `npm install` in a text editor, rewrite the version of "graceful-fs" in the "dependencies" section.

  "graceful-fs": "^3.0.0", to "graceful-fs": "^4.1.2",

Run `npm install` again and then `npm run release`.

-----
I am sorry if it is rude or inappropriate to you, since I use the online translation site.
